# language and language version travis is expecting
language: python
python:
    - '3.6'


# only need docker as it will run every other service
services:
    - docker

# runs docker-compose on travis
before_script: pip install docker-compose

# script to test and lint code before travis automation begins
script:
    - docker-compose run app sh -c 'python manage.py test && flake8'