version: '3'


services:
    app:
        # setting context to root directory
        build: 
            context: .
        ports:
            - '8000:8000'
        # maps app directory in project to app directory in docker image and updates docker when app directory is changed
        volumes: 
            - ./app:/app
        # runs wait for db to ensure db is online and migrates models
        # runs the development server on all available ip's on docker container on port 8000
        command: >
            sh -c 'python manage.py wait_for_db && 
                   python manage.py migrate &&
                   python manage.py runserver 0.0.0.0:8000'
        environment: 
            - DB_HOST=db
            - DB_NAME=app
            - DB_USER=postgres
            - DB_PASS=password
        # setting app service to depend on db 
        depends_on: 
            - db
    db:
        image: postgres:12-alpine
        # setting environment variables for database
        environment :
            - POSTGRES_DB=app
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password 

            